### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by aaesis** [pulkitjalan/google-apiclient#9]
Just wanted to know where to start the google API drive created by you. I mean do you have any demo? I setup credentials already. In laravel controller I added something like this:

$client = Google::getClient();
$service = new Google_Service_Drive($client);

got an error Class 'App\Http\Controllers\Google_Service_Drive' not found. I just wanted to use the google drive api all through way in my application. GET files details and links.

**Comment by pulkitjalan** [comment]
I don't have any demos. The reason you are getting the error is because Google_Service_Drive is not in a namespaces do your controller is. Adding a \ behind it will resolve the error.

You can also go Google::make('drive'); which will automatically resolve the service and return the service instance as mentioned in the readme.
